[package]
name = "state"
version = "0.1.0"
edition = "2021"

[dependencies]
artisan_middleware = "1.5.2"
config = "0.14.0"
dusa_collection_utils = "2.6.3"
serde = "1.0.210"
serde_json = "1.0.128"
toml = "0.8.19"
colored = "2.1.0"